const allProduct = [
    //의자 카테고리
    { 
        id: 1, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-1.jpg", 
        hoverImg: "chair-hv-1.jpg",
    },
    { 
        id: 2, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-2.jpg", 
        hoverImg: "chair-hv-2.png",
    },
    { 
        id: 3, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-3.jpg", 
        hoverImg: "chair-hv-3.jpg",
    },
    { 
        id: 4, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-4.png", 
        hoverImg: "chair-hv-4.png",
    },
    { 
        id: 5, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-5.jpg", 
        hoverImg: "chair-hv-5.jpg",
    },
    { 
        id: 6, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-6.jpg", 
        hoverImg: "chair-hv-6.jpg",
    },
    { 
        id: 7, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-7.jpg", 
        hoverImg: "chair-hv-7.jpg",
    },
    { 
        id: 8, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-8.jpg", 
        hoverImg: "chair-hv-8.png",
    },
    { 
        id: 9, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-9.jpg", 
        hoverImg: "chair-hv-9.jpg",
    },
    { 
        id: 10, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-10.png", 
        hoverImg: "chair-hv-10.png",
    },
    { 
        id: 11, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-11.jpg", 
        hoverImg: "chair-hv-11.png",
    },
    { 
        id: 12, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-12.png", 
        hoverImg: "chair-hv-12.jpg",
    },
    { 
        id: 13, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-13.jpg", 
        hoverImg: "chair-hv-13.png",
    },
    { 
        id: 14, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-14.jpg", 
        hoverImg: "chair-hv-14.jpg",
    },
    { 
        id: 15, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-15.jpg", 
        hoverImg: "chair-hv-15.png",
    },
    { 
        id: 16, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-16.jpg", 
        hoverImg: "chair-hv-16.png",
    },
    { 
        id: 17, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-17.jpg", 
        hoverImg: "chair-hv-17.jpg",
    },
    { 
        id: 18, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-18.png", 
        hoverImg: "chair-hv-18.png",
    },
    { 
        id: 19, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-19.png", 
        hoverImg: "chair-hv-19.png",
    },
    { 
        id: 20, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-20.png", 
        hoverImg: "chair-hv-20.png",
    },
    { 
        id: 21, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-21.jpg", 
        hoverImg: "chair-hv-21.png",
    },
    { 
        id: 22, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-22.png", 
        hoverImg: "chair-hv-22.png",
    },
    { 
        id: 23, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-23.png", 
        hoverImg: "chair-hv-23.png",
    },
    { 
        id: 24, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-24.png", 
        hoverImg: "chair-hv-24.png",
    },
    { 
        id: 25, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-25.png", 
        hoverImg: "chair-hv-25.png",
    },
    { 
        id: 26, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-26.jpg", 
        hoverImg: "chair-hv-26.png",
    },
    { 
        id: 27, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "450,000", 
        img: "chair-27.png", 
        hoverImg: "chair-hv-27.png",
    },
    
    //책상 카테고리
    { 
        id: 28, 
        category: "desk", 
        name: "2UC  MINT TABLE", 
        price: "850,000", 
        img: "desk-1.jpg", 
        hoverImg: "desk-hv-1.jpg",
    },
    { 
        id: 29, 
        category: "desk", 
        name: "2UC STEEL CONSOL", 
        price: "740,000 ", 
        img: "desk-2.jpg", 
        hoverImg: "desk-hv-2.jpg",
    },
    { 
        id: 30, 
        category: "desk", 
        name: "2UC WOOD EDGE TABLE", 
        price: "945,000", 
        img: "desk-3.jpg", 
        hoverImg: "desk-hv-3.jpg",
    },
    { 
        id: 31, 
        category: "desk", 
        name: "2UC 테이블", 
        price: "1,000,000", 
        img: "desk-4.jpg", 
        hoverImg: "desk-hv-4.jpg",
    },
    { 
        id: 32, 
        category: "desk", 
        name: "100 VINTAGE TABLE", 
        price: "960,000 ", 
        img: "desk-5.jpg", 
        hoverImg: "desk-hv-5.jpg",
    },
    { 
        id: 33, 
        category: "desk", 
        name: "500 HALF CONSOLE", 
        price: "45 0,000", 
        img: "desk-6.jpg", 
        hoverImg: "desk-hv-6.jpg",
    },
    { 
        id: 34, 
        category: "desk", 
        name: "704me table", 
        price: "1,400,000 ", 
        img: "desk-7.jpg", 
        hoverImg: "desk-hv-7.jpg",
    },
    { 
        id: 35, 
        category: "desk", 
        name: "750 Square Table", 
        price: "880,000", 
        img: "desk-8.jpg", 
        hoverImg: "desk-hv-8.jpg",
    },
    { 
        id: 36, 
        category: "desk", 
        name: "800 WOOD EDGE TABLE", 
        price: "920,000", 
        img: "desk-9.jpg", 
        hoverImg: "desk-hv-9.jpg",
    },
    { 
        id: 37, 
        category: "desk", 
        name: "berlin oval table", 
        price: "1,200,000", 
        img: "desk-10.jpg", 
        hoverImg: "desk-hv-10.jpg",
    },
    { 
        id: 38, 
        category: "desk", 
        name: "Berlin rec table", 
        price: "1,200,000", 
        img: "desk-11.jpg", 
        hoverImg: "desk-hv-11.jpg",
    },
    { 
        id: 39, 
        category: "desk", 
        name: "berlin table pedestal table", 
        price: "1,200,000", 
        img: "desk-12.jpg", 
        hoverImg: "desk-hv-12.jpg",
    },
    { 
        id: 40, 
        category: "desk", 
        name: "Berlin TABLE SE", 
        price: "1,200,000", 
        img: "desk-13.jpg", 
        hoverImg: "desk-hv-13.jpg",
    },
    { 
        id: 41, 
        category: "desk", 
        name: "Berlin table", 
        price: "1,200,000", 
        img: "desk-14.jpg", 
        hoverImg: "desk-hv-14.jpg",
    },
    { 
        id: 42, 
        category: "desk", 
        name: "bkk side table & stool", 
        price: "1,200,000", 
        img: "desk-15.jpg", 
        hoverImg: "desk-hv-15.jpg",
    },
    { 
        id: 43, 
        category: "desk", 
        name: "Black rec table", 
        price: "1,200,000", 
        img: "desk-16.jpg", 
        hoverImg: "desk-hv-16.jpg",
    },
    { 
        id: 44, 
        category: "desk", 
        name: "bora side table2", 
        price: "1,200,000", 
        img: "desk-17.jpg", 
        hoverImg: "desk-hv-17.jpg",
    },
    { 
        id: 45, 
        category: "desk", 
        name: "bora steel & side table", 
        price: "1,200,000 ", 
        img: "desk-18.jpg", 
        hoverImg: "desk-hv-18.jpg",
    },
    { 
        id: 46, 
        category: "desk", 
        name: "bora table", 
        price: "850,000", 
        img: "desk-19.jpg", 
        hoverImg: "desk-hv-19.jpg",
    },
    { 
        id: 47, 
        category: "desk", 
        name: "Classic half table ", 
        price: "850,000", 
        img: "desk-20.jpg", 
        hoverImg: "desk-hv-20.jpg",
    },
    { 
        id: 48, 
        category: "desk", 
        name: "classic Table 2 ", 
        price: "850,000", 
        img: "desk-21.jpg", 
        hoverImg: "desk-hv-21.jpg",
    },
    { 
        id: 49, 
        category: "desk", 
        name: "Classic Table", 
        price: "850,000", 
        img: "desk-22.jpg", 
        hoverImg: "desk-hv-22.jpg",
    },
    { 
        id: 50, 
        category: "desk", 
        name: "Color Circle Table", 
        price: "850,000", 
        img: "desk-23.jpg", 
        hoverImg: "desk-hv-23.jpg",
    },
    { 
        id: 51, 
        category: "desk", 
        name: "egg sofa table", 
        price: "850,000", 
        img: "desk-24.jpg", 
        hoverImg: "desk-hv-24.jpg",
    },
    { 
        id: 52, 
        category: "desk", 
        name: "egg table SE", 
        price: "850,000", 
        img: "desk-25.jpg", 
        hoverImg: "desk-hv-25.jpg",
    },
    { 
        id: 53, 
        category: "desk", 
        name: "Five mint table", 
        price: "850,000", 
        img: "desk-26.jpg", 
        hoverImg: "desk-hv-26.jpg",
    },
    { 
        id: 54, 
        category: "desk", 
        name: "Ginza table", 
        price: "850,000", 
        img: "desk-27.jpg", 
        hoverImg: "desk-hv-27.jpg",
    },
    { 
        id: 55, 
        category: "desk", 
        name: "H GLASS TABLE", 
        price: "850,000", 
        img: "desk-28.jpg", 
        hoverImg: "desk-hv-28.jpg",
    },
    { 
        id: 56, 
        category: "desk", 
        name: "H STOOL", 
        price: "850,000", 
        img: "desk-29.jpg", 
        hoverImg: "desk-hv-29.jpg",
    },
    { 
        id: 57, 
        category: "desk", 
        name: "H TABLE", 
        price: "850,000", 
        img: "desk-30.jpg", 
        hoverImg: "desk-hv-30.jpg",
    },
    { 
        id: 58, 
        category: "desk", 
        name: "Mid Table", 
        price: "850,000", 
        img: "desk-31.jpg", 
        hoverImg: "desk-hv-31.jpg",
    },
    { 
        id: 59, 
        category: "desk", 
        name: "One leg Table", 
        price: "850,000", 
        img: "desk-32.jpg", 
        hoverImg: "desk-hv-32.jpg",
    },
    { 
        id: 60, 
        category: "desk", 
        name: "ORANGE CONSOLE", 
        price: "850,000", 
        img: "desk-33.jpg", 
        hoverImg: "desk-hv-33.jpg",
    },
    { 
        id: 61, 
        category: "desk", 
        name: "oval steel consol", 
        price: "850,000", 
        img: "desk-34.jpg", 
        hoverImg: "desk-hv-34.jpg",
    },
    { 
        id: 62, 
        category: "desk", 
        name: "rainbow table ", 
        price: "850,000", 
        img: "desk-35.jpg", 
        hoverImg: "desk-hv-35.jpg",
    },
    { 
        id: 63, 
        category: "desk", 
        name: "san table", 
        price: "850,000", 
        img: "desk-36.jpg", 
        hoverImg: "desk-hv-36.jpg",
    },
    { 
        id: 64, 
        category: "desk", 
        name: "Side Bench", 
        price: "850,000", 
        img: "desk-37.jpg", 
        hoverImg: "desk-hv-37.jpg",
    },
    { 
        id: 65, 
        category: "desk", 
        name: "STEEL TABLE", 
        price: "850,000", 
        img: "desk-38.jpg", 
        hoverImg: "desk-hv-38.jpg",
    },
    { 
        id: 66, 
        category: "desk", 
        name: "StraightLine Table", 
        price: "850,000", 
        img: "desk-39.jpg", 
        hoverImg: "desk-hv-39.jpg",
    },
    { 
        id: 67, 
        category: "desk", 
        name: "triangle table", 
        price: "850,000", 
        img: "desk-40.jpg", 
        hoverImg: "desk-hv-40.jpg",
    },
    { 
        id: 68, 
        category: "desk", 
        name: "UNDER TABLE", 
        price: "850,000", 
        img: "desk-41.jpg", 
        hoverImg: "desk-hv-41.jpg",
    },
    { 
        id: 69, 
        category: "desk", 
        name: "Vertical Table", 
        price: "850,000", 
        img: "desk-42.jpg", 
        hoverImg: "desk-hv-42.jpg",
    },
    { 
        id: 70, 
        category: "desk", 
        name: "Vertical2 Table", 
        price: "850,000", 
        img: "desk-43.jpg", 
        hoverImg: "desk-hv-43.jpg",
    },
    { 
        id: 71, 
        category: "desk", 
        name: "weimar table", 
        price: "850,000", 
        img: "desk-44.jpg", 
        hoverImg: "desk-hv-44.jpg",
    },
    { 
        id: 72, 
        category: "desk", 
        name: "white table", 
        price: "850,000", 
        img: "desk-45.jpg", 
        hoverImg: "desk-hv-45.jpg",
    },
    { 
        id: 73, 
        category: "desk", 
        name: "wood circle table(wood)", 
        price: "850,000", 
        img: "desk-46.jpg", 
        hoverImg: "desk-hv-46.jpg",
    },
    { 
        id: 74, 
        category: "desk", 
        name: "wood circle table", 
        price: "850,000", 
        img: "desk-47.jpg", 
        hoverImg: "desk-hv-47.jpg",
    },
    { 
        id: 75, 
        category: "desk", 
        name: "Wood Half Table", 
        price: "850,000", 
        img: "desk-48.jpg", 
        hoverImg: "desk-hv-48.jpg",
    },
    { 
        id: 76, 
        category: "desk", 
        name: "ㅠ Table", 
        price: "850,000", 
        img: "desk-49.jpg", 
        hoverImg: "desk-hv-49.jpg",
    },
    { 
        id: 77, 
        category: "desk", 
        name: "2UC HALF TABLE2", 
        price: "850,000", 
        img: "desk-50.jpg", 
        hoverImg: "desk-hv-50.jpg",
    },
    { 
        id: 78, 
        category: "desk", 
        name: "", 
        price: "850,000", 
        img: "desk-51.jpg", 
        hoverImg: "desk-hv-51.jpg",
    },
    { 
        id: 79, 
        category: "desk", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "desk-52.jpg", 
        hoverImg: "desk-hv-52.jpg",
    },
    { 
        id: 80, 
        category: "desk", 
        name: "2UC HALF TABLE (2) ", 
        price: "850,000", 
        img: "desk-53.jpg", 
        hoverImg: "desk-hv-53.jpg",
    },

    //소파 카테고리
    { 
        id: 81, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-1.png", 
        hoverImg: "sofa-hv-1.png",
    },
    { 
        id: 82, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-2.png", 
        hoverImg: "sofa-hv-2.png",
    },
    { 
        id: 83, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-3.png", 
        hoverImg: "sofa-hv-3.png",
    },
    { 
        id: 84, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-4.jpg", 
        hoverImg: "sofa-hv-4.png",
    },
    { 
        id: 85, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-5.png", 
        hoverImg: "sofa-hv-5.png",
    },
    { 
        id: 86, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-6.png", 
        hoverImg: "sofa-hv-6.png",
    },
    { 
        id: 87, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-7.png", 
        hoverImg: "sofa-hv-7.png",
    },
    { 
        id: 88, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "850,000", 
        img: "sofa-8.png", 
        hoverImg: "sofa-hv-8.png",
    },
]