const allProduct = [
    //의자 카테고리
    { 
        id: 1, 
        category: "chair", 
        name: "54 CHAIR - TEDDY MUSTARD", 
        price: "450000", 
        img: "chair-1.jpg", 
        hoverImg: "chair-hv-1.jpg",
        detailImages: [],
        descriptionImg:"dt-chair-1.jpg",
    },
    { 
        id: 2, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "550000", 
        img: "chair-2.jpg", 
        hoverImg: "chair-hv-2.png",
        detailImages: [],
        descriptionImg:"dt-chair-2.jpg",
    },
    { 
        id: 3, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "650000", 
        img: "chair-3.jpg", 
        hoverImg: "chair-hv-3.jpg",
        detailImages: [],
        descriptionImg:"dt-chair-3.jpg",
    },
    { 
        id: 4, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "360000", 
        img: "chair-4.png", 
        hoverImg: "chair-hv-4.png",
        detailImages: [],
        descriptionImg:"dt-chair-4.jpg",
    },
    { 
        id: 5, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "4560000", 
        img: "chair-5.jpg", 
        hoverImg: "chair-hv-5.jpg",
        detailImages: [],
        descriptionImg:"dt-chair-5.jpg",
    },
    { 
        id: 6, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "620000", 
        img: "chair-6.jpg", 
        hoverImg: "chair-hv-6.jpg",
    },
    { 
        id: 7, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "840000", 
        img: "chair-7.jpg", 
        hoverImg: "chair-hv-7.jpg",
    },
    { 
        id: 8, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "640000", 
        img: "chair-8.jpg", 
        hoverImg: "chair-hv-8.png",
    },
    { 
        id: 9, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "350000", 
        img: "chair-9.jpg", 
        hoverImg: "chair-hv-9.jpg",
    },
    { 
        id: 10, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "550000", 
        img: "chair-10.png", 
        hoverImg: "chair-hv-10.png",
    },
    { 
        id: 11, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "620000", 
        img: "chair-11.jpg", 
        hoverImg: "chair-hv-11.png",
    },
    { 
        id: 12, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "850000", 
        img: "chair-12.png", 
        hoverImg: "chair-hv-12.jpg",
    },
    { 
        id: 13, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "630000", 
        img: "chair-13.jpg", 
        hoverImg: "chair-hv-13.png",
    },
    { 
        id: 14, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "740000", 
        img: "chair-14.jpg", 
        hoverImg: "chair-hv-14.jpg",
    },
    { 
        id: 15, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "650000", 
        img: "chair-15.jpg", 
        hoverImg: "chair-hv-15.png",
    },
    { 
        id: 16, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "770000", 
        img: "chair-16.jpg", 
        hoverImg: "chair-hv-16.png",
    },
    { 
        id: 17, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "560000", 
        img: "chair-17.jpg", 
        hoverImg: "chair-hv-17.jpg",
    },
    { 
        id: 18, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "580000", 
        img: "chair-18.png", 
        hoverImg: "chair-hv-18.png",
    },
    { 
        id: 19, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "470000", 
        img: "chair-19.png", 
        hoverImg: "chair-hv-19.png",
    },
    { 
        id: 20, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "510000", 
        img: "chair-20.png", 
        hoverImg: "chair-hv-20.png",
    },
    { 
        id: 21, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "850000", 
        img: "chair-21.jpg", 
        hoverImg: "chair-hv-21.png",
    },
    { 
        id: 22, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "540000", 
        img: "chair-22.png", 
        hoverImg: "chair-hv-22.png",
    },
    { 
        id: 23, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "610000", 
        img: "chair-23.png", 
        hoverImg: "chair-hv-23.png",
    },
    { 
        id: 24, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "580000", 
        img: "chair-24.png", 
        hoverImg: "chair-hv-24.png",
    },
    { 
        id: 25, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "490000", 
        img: "chair-25.png", 
        hoverImg: "chair-hv-25.png",
    },
    { 
        id: 26, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "580000", 
        img: "chair-26.jpg", 
        hoverImg: "chair-hv-26.png",
    },
    { 
        id: 27, 
        category: "chair", 
        name: "Lumiere White Chair", 
        price: "670000", 
        img: "chair-27.png", 
        hoverImg: "chair-hv-27.png",
    },
    
    //책상 카테고리
    { 
        id: 28, 
        category: "desk", 
        name: "2UC  MINT TABLE", 
        price: "850000", 
        img: "desk-1.jpg", 
        hoverImg: "desk-hv-1.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-1.jpg",
    },
    { 
        id: 29, 
        category: "desk", 
        name: "2UC STEEL CONSOL", 
        price: "740000 ", 
        img: "desk-2.jpg", 
        hoverImg: "desk-hv-2.jpg",
    },
    { 
        id: 30, 
        category: "desk", 
        name: "2UC WOOD EDGE TABLE", 
        price: "945000", 
        img: "desk-3.jpg", 
        hoverImg: "desk-hv-3.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-3.jpg",
    },
    { 
        id: 31, 
        category: "desk", 
        name: "2UC 테이블", 
        price: "1000000", 
        img: "desk-4.jpg", 
        hoverImg: "desk-hv-4.jpg",
    },
    { 
        id: 32, 
        category: "desk", 
        name: "100 VINTAGE TABLE", 
        price: "960000 ", 
        img: "desk-5.jpg", 
        hoverImg: "desk-hv-5.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-5.jpg",
    },
    { 
        id: 33, 
        category: "desk", 
        name: "500 HALF CONSOLE", 
        price: "750000", 
        img: "desk-6.jpg", 
        hoverImg: "desk-hv-6.jpg",
    },
    { 
        id: 34, 
        category: "desk", 
        name: "704me table", 
        price: "1400000 ", 
        img: "desk-7.jpg", 
        hoverImg: "desk-hv-7.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-7.jpg",
    },
    { 
        id: 35, 
        category: "desk", 
        name: "750 Square Table", 
        price: "880000", 
        img: "desk-8.jpg", 
        hoverImg: "desk-hv-8.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-8.jpg",
    },
    { 
        id: 36, 
        category: "desk", 
        name: "800 WOOD EDGE TABLE", 
        price: "920000", 
        img: "desk-9.jpg", 
        hoverImg: "desk-hv-9.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-9.jpg",
    },
    { 
        id: 37, 
        category: "desk", 
        name: "berlin oval table", 
        price: "1500000", 
        img: "desk-10.jpg", 
        hoverImg: "desk-hv-10.jpg",
    },
    { 
        id: 38, 
        category: "desk", 
        name: "Berlin rec table", 
        price: "1600000", 
        img: "desk-11.jpg", 
        hoverImg: "desk-hv-11.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-11.jpg",
    },
    { 
        id: 39, 
        category: "desk", 
        name: "berlin table pedestal table", 
        price: "940000", 
        img: "desk-12.jpg", 
        hoverImg: "desk-hv-12.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-12.jpg", 
    },
    { 
        id: 40, 
        category: "desk", 
        name: "Berlin TABLE SE", 
        price: "1400000", 
        img: "desk-13.jpg", 
        hoverImg: "desk-hv-13.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-13.jpg",
    },
    { 
        id: 41, 
        category: "desk", 
        name: "Berlin table", 
        price: "1600000", 
        img: "desk-14.jpg", 
        hoverImg: "desk-hv-14.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-14.jpg",
    },
    { 
        id: 42, 
        category: "desk", 
        name: "bkk side table & stool", 
        price: "1500000", 
        img: "desk-15.jpg", 
        hoverImg: "desk-hv-15.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-15.jpg",
    },
    { 
        id: 43, 
        category: "desk", 
        name: "Black rec table", 
        price: "900000", 
        img: "desk-16.jpg", 
        hoverImg: "desk-hv-16.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-16.jpg",
    },
    { 
        id: 44, 
        category: "desk", 
        name: "bora side table2", 
        price: "800000", 
        img: "desk-17.jpg", 
        hoverImg: "desk-hv-17.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-17.jpg",
    },
    { 
        id: 45, 
        category: "desk", 
        name: "bora steel & side table", 
        price: "880000 ", 
        img: "desk-18.jpg", 
        hoverImg: "desk-hv-18.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-18.jpg",
    },
    { 
        id: 46, 
        category: "desk", 
        name: "bora table", 
        price: "850000", 
        img: "desk-19.jpg", 
        hoverImg: "desk-hv-19.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-19.jpg",
    },
    { 
        id: 47, 
        category: "desk", 
        name: "Classic half table ", 
        price: "960000", 
        img: "desk-20.jpg", 
        hoverImg: "desk-hv-20.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-20.jpg",
    },
    { 
        id: 48, 
        category: "desk", 
        name: "classic Table 2 ", 
        price: "990000", 
        img: "desk-21.jpg", 
        hoverImg: "desk-hv-21.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-21.jpg",
    },
    { 
        id: 49, 
        category: "desk", 
        name: "Classic Table", 
        price: "1200000", 
        img: "desk-22.jpg", 
        hoverImg: "desk-hv-22.jpg",
    },
    { 
        id: 50, 
        category: "desk", 
        name: "Color Circle Table", 
        price: "1530000", 
        img: "desk-23.jpg", 
        hoverImg: "desk-hv-23.jpg",
        detailImages: ["desk-23-1.jpg", "desk-23-2.jpg", "desk-23-3.jpg"],
        descriptionImg:"dt-desk-23.jpg",
    },
    { 
        id: 51, 
        category: "desk", 
        name: "egg sofa table", 
        price: "920000", 
        img: "desk-24.jpg", 
        hoverImg: "desk-hv-24.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-24.jpg",
    },
    { 
        id: 52, 
        category: "desk", 
        name: "egg table SE", 
        price: "1100000", 
        img: "desk-25.jpg", 
        hoverImg: "desk-hv-25.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-25.jpg",
    },
    { 
        id: 53, 
        category: "desk", 
        name: "Five mint table", 
        price: "1300000", 
        img: "desk-26.jpg", 
        hoverImg: "desk-hv-26.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-26.jpg",
    },
    { 
        id: 54, 
        category: "desk", 
        name: "Ginza table", 
        price: "960000", 
        img: "desk-27.jpg", 
        hoverImg: "desk-hv-27.jpg",
    },
    { 
        id: 55, 
        category: "desk", 
        name: "H GLASS TABLE", 
        price: "1040000", 
        img: "desk-28.jpg", 
        hoverImg: "desk-hv-28.jpg",
    },
    { 
        id: 56, 
        category: "desk", 
        name: "H STOOL", 
        price: "910000", 
        img: "desk-29.jpg", 
        hoverImg: "desk-hv-29.jpg",
    },
    { 
        id: 57, 
        category: "desk", 
        name: "H TABLE", 
        price: "1100000", 
        img: "desk-30.jpg", 
        hoverImg: "desk-hv-30.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-30.jpg",
    },
    { 
        id: 58, 
        category: "desk", 
        name: "Mid Table", 
        price: "1080000", 
        img: "desk-31.jpg", 
        hoverImg: "desk-hv-31.jpg",
    },
    { 
        id: 59, 
        category: "desk", 
        name: "One leg Table", 
        price: "1040000", 
        img: "desk-32.jpg", 
        hoverImg: "desk-hv-32.jpg",
    },
    { 
        id: 60, 
        category: "desk", 
        name: "ORANGE CONSOLE", 
        price: "990000", 
        img: "desk-33.jpg", 
        hoverImg: "desk-hv-33.jpg",
    },
    { 
        id: 61, 
        category: "desk", 
        name: "oval steel consol", 
        price: "1050000", 
        img: "desk-34.jpg", 
        hoverImg: "desk-hv-34.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-34.jpg",
    },
    { 
        id: 62, 
        category: "desk", 
        name: "rainbow table ", 
        price: "980000", 
        img: "desk-35.jpg", 
        hoverImg: "desk-hv-35.jpg",
    },
    { 
        id: 63, 
        category: "desk", 
        name: "san table", 
        price: "850000", 
        img: "desk-36.jpg", 
        hoverImg: "desk-hv-36.jpg",
    },
    { 
        id: 64, 
        category: "desk", 
        name: "Side Bench", 
        price: "1000000", 
        img: "desk-37.jpg", 
        hoverImg: "desk-hv-37.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-37.jpg",
    },
    { 
        id: 65, 
        category: "desk", 
        name: "STEEL TABLE", 
        price: "1090000", 
        img: "desk-38.jpg", 
        hoverImg: "desk-hv-38.jpg",
    },
    { 
        id: 66, 
        category: "desk", 
        name: "StraightLine Table", 
        price: "1200000", 
        img: "desk-39.jpg", 
        hoverImg: "desk-hv-39.jpg",
    },
    { 
        id: 67, 
        category: "desk", 
        name: "triangle table", 
        price: "1400000", 
        img: "desk-40.jpg", 
        hoverImg: "desk-hv-40.jpg",
    },
    { 
        id: 68, 
        category: "desk", 
        name: "UNDER TABLE", 
        price: "2000000", 
        img: "desk-41.jpg", 
        hoverImg: "desk-hv-41.jpg",
    },
    { 
        id: 69, 
        category: "desk", 
        name: "Vertical Table", 
        price: "1100000", 
        img: "desk-42.jpg", 
        hoverImg: "desk-hv-42.jpg",
    },
    { 
        id: 70, 
        category: "desk", 
        name: "Vertical2 Table", 
        price: "1200000", 
        img: "desk-43.jpg", 
        hoverImg: "desk-hv-43.jpg",
    },
    { 
        id: 71, 
        category: "desk", 
        name: "weimar table", 
        price: "1050000", 
        img: "desk-44.jpg", 
        hoverImg: "desk-hv-44.jpg",
    },
    { 
        id: 72, 
        category: "desk", 
        name: "white table", 
        price: "950000", 
        img: "desk-45.jpg", 
        hoverImg: "desk-hv-45.jpg",
        detailImages: [],
        descriptionImg:"dt-desk-45.jpg",
    },
    { 
        id: 73, 
        category: "desk", 
        name: "wood circle table(wood)", 
        price: "910000", 
        img: "desk-46.jpg", 
        hoverImg: "desk-hv-46.jpg",
    },
    { 
        id: 74, 
        category: "desk", 
        name: "wood circle table", 
        price: "880000", 
        img: "desk-47.jpg", 
        hoverImg: "desk-hv-47.jpg",
    },
    { 
        id: 75, 
        category: "desk", 
        name: "Wood Half Table", 
        price: "1700000", 
        img: "desk-48.jpg", 
        hoverImg: "desk-hv-48.jpg",
    },
    { 
        id: 76, 
        category: "desk", 
        name: "ㅠ Table", 
        price: "1200000", 
        img: "desk-49.jpg", 
        hoverImg: "desk-hv-49.jpg",
    },
    { 
        id: 77, 
        category: "desk", 
        name: "2UC HALF TABLE2", 
        price: "1370000", 
        img: "desk-50.jpg", 
        hoverImg: "desk-hv-50.jpg",
        detailImages: ["desk-50-1.jpg", "desk-50-2.jpg", "desk-50-3.jpg"],
        descriptionImg:"dt-desk-50.jpg",
    },
    { 
        id: 78, 
        category: "desk", 
        name: "2UC TRIANGLE CONSOLE", 
        price: "990000", 
        img: "desk-51.jpg", 
        hoverImg: "desk-hv-51.jpg",
        detailImages: ["desk-51-1.jpg", "desk-51-2.jpg", "desk-51-3.jpg"],
        descriptionImg:"dt-desk-51.jpg",
    },
    { 
        id: 79, 
        category: "desk", 
        name: "2UC MINT TABLE", 
        price: "870000", 
        img: "desk-52.jpg", 
        hoverImg: "desk-hv-52.jpg",
    },
    { 
        id: 80, 
        category: "desk", 
        name: "2UC HALF TABLE (2) ", 
        price: "1060000", 
        img: "desk-53.jpg", 
        hoverImg: "desk-hv-53.jpg",
    },

    //소파 카테고리
    { 
        id: 81, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "1030000", 
        img: "sofa-1.png", 
        hoverImg: "sofa-hv-1.png",
        detailImages: [],
        descriptionImg:"dt-sofa-1.jpg",
    },
    { 
        id: 82, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "1100000", 
        img: "sofa-2.png", 
        hoverImg: "sofa-hv-2.png",
        detailImages: [],
        descriptionImg:"dt-sofa-2.jpg",
    },
    { 
        id: 83, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "1270000", 
        img: "sofa-3.png", 
        hoverImg: "sofa-hv-3.png",
        detailImages: [],
        descriptionImg:"dt-sofa-3.jpg",
    },
    { 
        id: 84, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "1560000", 
        img: "sofa-4.jpg", 
        hoverImg: "sofa-hv-4.png",
        detailImages: [],
        descriptionImg:"dt-sofa-4.jpg",
    },
    { 
        id: 85, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "910000", 
        img: "sofa-5.png", 
        hoverImg: "sofa-hv-5.png",
    },
    { 
        id: 86, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "930000", 
        img: "sofa-6.png", 
        hoverImg: "sofa-hv-6.png",
    },
    { 
        id: 87, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "840000", 
        img: "sofa-7.png", 
        hoverImg: "sofa-hv-7.png",
    },
    { 
        id: 88, 
        category: "sofa", 
        name: "2UC MINT TABLE", 
        price: "1030000", 
        img: "sofa-8.png", 
        hoverImg: "sofa-hv-8.png",
    },

    //조명 카테고리
    { 
        id: 89, 
        category: "lamp", 
        name: "AETHER", 
        price: "670000", 
        img: "lamp-1.jpg", 
        hoverImg: "lamp-hv-1.png",
        detailImages: [],
        descriptionImg:"dt-lamp-1.jpg",
    },
    { 
        id: 90, 
        category: "lamp", 
        name: "ANTON-CERAMIC", 
        price: "890000", 
        img: "lamp-2.jpg", 
        hoverImg: "lamp-hv-2.png",
        detailImages: [],
        descriptionImg:"dt-lamp-2.jpg",
    },
    { 
        id: 90, 
        category: "lamp", 
        name: "CIRKUS-WALL-LAMP", 
        price: "850000", 
        img: "lamp-3.png", 
        hoverImg: "lamp-hv-3.png",
        detailImages: [],
        descriptionImg:"dt-lamp-3.jpg",
    },
    { 
        id: 91, 
        category: "lamp", 
        name: "CL4-Table-Lamp", 
        price: "930000", 
        img: "lamp-4.png", 
        hoverImg: "lamp-hv-4.png",
        detailImages: [],
        descriptionImg:"dt-lamp-4.jpg",
    },
    { 
        id: 92, 
        category: "lamp", 
        name: "DALU", 
        price: "830000", 
        img: "lamp-5.png", 
        hoverImg: "lamp-hv-5.png",
        detailImages: [],
        descriptionImg:"dt-lamp-5.jpg",
    },
    { 
        id: 93, 
        category: "lamp", 
        name: "FLIP-Floor-Chocolate", 
        price: "970000", 
        img: "lamp-6.png", 
        hoverImg: "lamp-hv-6.png",
        detailImages: [],
        descriptionImg:"dt-lamp-6.jpg",
    },
    { 
        id: 94, 
        category: "lamp", 
        name: "FLIP-Table-Chocolate", 
        price: "790000", 
        img: "lamp-7.png", 
        hoverImg: "lamp-hv-7.png",
        detailImages: [],
        descriptionImg:"dt-lamp-7.jpg",
    },
    { 
        id: 95, 
        category: "lamp", 
        name: "Fontanatella-Large", 
        price: "680000", 
        img: "lamp-8.png", 
        hoverImg: "lamp-hv-8.png",
        detailImages: [],
        descriptionImg:"dt-lamp-8.jpg",
    },
    { 
        id: 96, 
        category: "lamp", 
        name: "MAYFAIR-MINI-TABLE-LAMP", 
        price: "780000", 
        img: "lamp-9.png", 
        hoverImg: "lamp-hv-9.png",
        detailImages: [],
        descriptionImg:"dt-lamp-9.jpg",
    },
    { 
        id: 97, 
        category: "lamp", 
        name: "Multi-Lite-Portable-Lamp", 
        price: "900000", 
        img: "lamp-10.png", 
        hoverImg: "lamp-hv-10.png",
    },
    { 
        id: 98, 
        category: "lamp", 
        name: "NESSINO", 
        price: "640000", 
        img: "lamp-11.jpg", 
        hoverImg: "lamp-hv-11.png",
    },
    { 
        id: 99, 
        category: "lamp", 
        name: "NESSO", 
        price: "600000", 
        img: "lamp-12.png", 
        hoverImg: "lamp-hv-12.png",
    },
    { 
        id: 100, 
        category: "lamp", 
        name: "APANTHELLA-160-PORTABLE-V3ETHER", 
        price: "590000", 
        img: "lamp-13.png", 
        hoverImg: "lamp-hv-13.png",
    },
    { 
        id: 89, 
        category: "lamp", 
        name: "PH-80-TABLE-LAMP", 
        price: "670000", 
        img: "lamp-14.png", 
        hoverImg: "lamp-hv-14.png",
    },
    { 
        id: 89, 
        category: "lamp", 
        name: "Rumee-220-Portable", 
        price: "910000", 
        img: "lamp-15.png", 
        hoverImg: "lamp-hv-15.png",
    },
    { 
        id: 89, 
        category: "lamp", 
        name: "Sintesi", 
        price: "660000", 
        img: "lamp-16.jpg", 
        hoverImg: "lamp-hv-16.png",
    },

    // 책장 카테고리
    { 
        id: 90, 
        category: "bookself", 
        name: "2UC COLOR CABINET", 
        price: "1020000", 
        img: "booself-1.jpg", 
        hoverImg: "booself-hv-1.jpg",
        
    },
    { 
        id: 91, 
        category: "bookself", 
        name: "balance steel shelf", 
        price: "1200000", 
        img: "booself-2.jpg", 
        hoverImg: "booself-hv-2.jpg",
        detailImages: [],
        descriptionImg:"dt-book-2.jpg",
    },
    { 
        id: 92, 
        category: "bookself", 
        name: "CLASSON BEDSIDE", 
        price: "1070000", 
        img: "booself-3.jpg", 
        hoverImg: "booself-hv-3.jpg",
        detailImages: [],
        descriptionImg:"dt-book-3.jpg",
    },
    { 
        id: 93, 
        category: "bookself", 
        name: "CLASSON LOW CHEST", 
        price: "1200000", 
        img: "booself-4.jpg", 
        hoverImg: "bookself-hv-4.jpg",
        detailImages: [],
        descriptionImg:"dt-book-4.jpg",
    },
    { 
        id: 94, 
        category: "bookself", 
        name: "CLASSON SIDEBOARD", 
        price: "1090000", 
        img: "booself-5.jpg", 
        hoverImg: "bookself-hv-5.jpg",
        detailImages: [],
        descriptionImg:"dt-book-5.jpg",
    },
    { 
        id: 95, 
        category: "bookself", 
        name: "CLASSON TALL CHEST", 
        price: "98000", 
        img: "booself-6.jpg", 
        hoverImg: "bookself-hv-6.jpg",
        detailImages: [],
        descriptionImg:"dt-book-6.jpg",
    },
    { 
        id: 96, 
        category: "bookself", 
        name: "Cradle", 
        price: "1020000", 
        img: "booself-7.jpg", 
        hoverImg: "booself-hv-7.jpg",
        detailImages: [],
        descriptionImg:"dt-book-7.jpg",
    },
    { 
        id: 97, 
        category: "bookself", 
        name: "GLASS SHELF", 
        price: "1200000", 
        img: "booself-8.jpg", 
        hoverImg: "booself-hv-8.jpg",
        detailImages: [],
        descriptionImg:"dt-book-8.jpg",
    },
    { 
        id: 98, 
        category: "bookself", 
        name: "Knud Holscher Roller Cabine", 
        price: "1000000", 
        img: "booself-9.jpg", 
        hoverImg: "booself-hv-9.jpg",
        detailImages: [],
        descriptionImg:"dt-book-9.jpg",
    },
    { 
        id: 99, 
        category: "bookself", 
        name: "Nok storage", 
        price: "1330000", 
        img: "booself-10.jpg", 
        hoverImg: "booself-hv-10.png",
    },
    { 
        id: 100, 
        category: "bookself", 
        name: "oki side table", 
        price: "1230000", 
        img: "booself-11.jpg", 
        hoverImg: "booself-hv-11.jpg",
    },
    { 
        id: 101, 
        category: "bookself", 
        name: "Paperback Wallsystem", 
        price: "1060000", 
        img: "booself-12.jpg", 
        hoverImg: "bookself-hv-12.jpg",
    },
    { 
        id: 102, 
        category: "bookself", 
        name: "S4-2 Display Cabinet", 
        price: "1000000", 
        img: "booself-13.jpg", 
        hoverImg: "booself-hv-13.jpg",
    },
    { 
        id: 103, 
        category: "bookself", 
        name: "S4-2 Display Cabinet", 
        price: "970000", 
        img: "booself-14.jpg", 
        hoverImg: "booself-hv-14.jpg",
    },
    { 
        id: 104, 
        category: "bookself", 
        name: "Steel shelf", 
        price: "1020000", 
        img: "booself-15.jpg", 
        hoverImg: "booself-hv-15.jpg",
    },
    { 
        id: 105, 
        category: "bookself", 
        name: "Tangled Cabinet - Taupe", 
        price: "1200000", 
        img: "booself-16.jpg", 
        hoverImg: "booself-hv-16.jpg",
    },
    { 
        id: 106, 
        category: "bookself", 
        name: "Tangled Show Case", 
        price: "850000", 
        img: "booself-17.jpg", 
        hoverImg: "booself-hv-17.jpg",
    },
    { 
        id: 107, 
        category: "bookself", 
        name: "TENSION SIDE TABLE", 
        price: "1090000", 
        img: "booself-18.jpg", 
        hoverImg: "booself-hv-18.jpg",
    },
    { 
        id: 108, 
        category: "bookself", 
        name: "three shelf", 
        price: "1100000", 
        img: "booself-19.jpg", 
        hoverImg: "bookself-hv-19.jpg",
    },
    { 
        id: 109, 
        category: "bookself", 
        name: "TRUNK LOW CABINET", 
        price: "1250000", 
        img: "booself-20.jpg", 
        hoverImg: "booself-hv-20.jpg",
    },
    { 
        id: 110, 
        category: "bookself", 
        name: "two shelf", 
        price: "1180000", 
        img: "booself-21.jpg", 
        hoverImg: "booself-hv-21.jpg",
    },
    // 베스트 제품
    
    { 
        id: 111, 
        category: "best", 
        name: "2UC MINT TABLE", 
        price: "910000", 
        img: "sofa-5.png", 
        hoverImg: "sofa-hv-5.png",
    },
    { 
        id: 112, 
        category: "best", 
        name: "NESSINO", 
        price: "640000", 
        img: "lamp-11.jpg", 
        hoverImg: "lamp-hv-11.png",
    },
    { 
        id: 113, 
        category: "best", 
        name: "Vertical Table", 
        price: "1100000", 
        img: "desk-45.jpg", 
        hoverImg: "desk-hv-45.jpg",
    },
    { 
        id: 114, 
        category: "best", 
        name: "2UC COLOR CABINET", 
        price: "1020000", 
        img: "booself-1.jpg", 
        hoverImg: "booself-hv-1.jpg",
    },
    { 
        id: 115, 
        category: "best", 
        name: "oki side table", 
        price: "1230000", 
        img: "booself-11.jpg", 
        hoverImg: "booself-hv-11.jpg",
    },
    { 
        id: 116, 
        category: "best", 
        name: "Sintesi", 
        price: "660000", 
        img: "lamp-16.jpg", 
        hoverImg: "lamp-hv-16.png",
    },
    { 
        id: 117, 
        category: "best", 
        name: "GLASS SHELF", 
        price: "1200000", 
        img: "booself-8.jpg", 
        hoverImg: "booself-hv-8.jpg",
    },
]